### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by m9810223** [m9810223/Mesida#1]
- [ ] replace triggers with events 
- [ ] module.exports ?
- [ ] cookie optional setting -> object
- [ ] google conversion 
- [ ] custom event
- [ ] configs collect script 
- [ ] separation functions in site code 
- [ ] triggers: push, check 
- [ ] publisher check 
- [ ] fetch wrapper 
- [ ] readme list functions 
- [x] webpack config
